- name: Install PGP
  ansible.builtin.apt:
    name: pgp
    state: present
    update_cache: true

- name: Import repository signing key
  ansible.builtin.apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Install PostgreSQL repository
  ansible.builtin.apt_repository:
    repo: "deb https://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
    filename: pgdg
    state: present

- name: Install PostgreSQL
  ansible.builtin.apt:
    name: "postgresql-{{ postgres_version }}"
    state: present
    update_cache: true

- name: Ensure PostgreSQL is running
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: true

- name: Update listen_addresses config
  ansible.builtin.lineinfile:
    path: /etc/postgresql/{{ postgres_version }}/main/postgresql.conf
    regex: "#listen_addresses"
    line: listen_addresses = '*'
  notify: Restart postgresql

- name: Update client authentication config
  ansible.builtin.lineinfile:
    path: /etc/postgresql/{{ postgres_version }}/main/pg_hba.conf
    insertafter: EOF
    line: host    all             all             {{ mac_ip_address }}/24            md5
  notify: Restart postgresql

- name: Set password for PostgreSQL user "postgres"
  ansible.builtin.command:
    cmd: psql -c "ALTER USER postgres WITH PASSWORD '{{ postgres_password }}';"
  become: true
  become_method: ansible.builtin.su
  become_user: postgres
  changed_when: true
