- name: Update and upgrade packages
  ansible.builtin.apt:
    update_cache: true

- name: Install required packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - dnsutils
    - git
    - dialog

- name: Ensure Pi-hole group exists
  ansible.builtin.group:
    name: pihole
    state: present

- name: Ensure Pi-hole user exists
  ansible.builtin.user:
    name: pihole
    group: pihole
    create_home: false
    shell: /bin/bash
    state: present

- name: Download Pi-Hole install script
  ansible.builtin.get_url:
    url: https://install.pi-hole.net
    dest: /root/pihole-install.sh
    mode: "0774"
    owner: root
    group: root

- name: Create pihole dir in etc
  ansible.builtin.file:
    path: /etc/pihole
    state: directory
    mode: "0755"
    owner: pihole
    group: pihole

- name: Create config setupVars.conf
  ansible.builtin.template:
    src: setupVars.conf.j2
    dest: /etc/pihole/setupVars.conf
    mode: "0644"
    owner: pihole
    group: pihole

- name: Pi-Hole automated install
  ansible.builtin.command:
    cmd: /root/pihole-install.sh --unattended
  changed_when: true

- name: Ensure Pi-hole is running
  ansible.builtin.service:
    name: pihole-FTL
    state: started
    enabled: true

- name: Add custom dns records
  ansible.builtin.lineinfile:
    path: /etc/pihole/custom.list
    line: "{{ item }}"
  loop: "{{ pihole_custom_dns_records }}"
